version: "3.1"

services:
  php-fpm:
    platform: linux/arm64/v8
    build: ./
    container_name: omr-webserver
    working_dir: /app
    domainname: omr.localhost
    volumes:
      - ./:/app
    environment:
      - COMPOSER_VERSION=2
    ports:
      - "80:80"